### ISSUE TITLE
Feature request: Countdown as Title messages

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#34]
**Is your feature request related to a problem? Please describe.**
It will be a lot of spam in chat with the 30, 20, 10, 5, 3, 2, 1 seconds messages in chat. Go modern, go title-messages!

**Describe the solution you'd like**
Change the countdown to be displayed in title messages instead. You could have time in the title, example 30, and then "seconds to hide" on the bottom line. With ability to change what you want to display yourself in the config.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by tylermurphy534** [comment]
Added in new 1.4.3 beta

**Comment by Nesseley** [comment]
I see you put the messages in the text above the toolbar instead of titles. I think titles will be much better as they are more visible to the players.

Also the first message about 30 seconds was still sent in chat, and the "START" message also was sent in chat. I would like for it all to be sent as title messages on the second line of titles.

**Comment by tylermurphy534** [comment]
Made it so you can switch beween CHAT, TITLE, or ACTIONBAR. If you choose TITLE, the "START" message doesn't display as the team title is showing then.

**Comment by Nesseley** [comment]
I downloaded the latest action build, but I don't see where to change what output I'm using? :)

**Comment by tylermurphy534** [comment]
This should be fixed now as it was an issue with me fixing the special characters turning into ? bug lol

**Comment by Nesseley** [comment]
The config.yml breaks and sends an error if I change it to "TITLE", changing it back to CHAT and the config is still broken. 
```
[10:12:40 INFO]: Nesseley issued server command: /hs reload
[10:12:40 WARN]: java.lang.RuntimeException: Invalid configuration in config file: plugins\HideAndSeek\config.yml
[10:12:40 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.configuration.ConfigManager.<init>(ConfigManager.java:83)
[10:12:40 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.configuration.ConfigManager.create(ConfigManager.java:40)
[10:12:40 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.configuration.Config.loadConfig(Config.java:147)
[10:12:40 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.command.Reload.execute(Reload.java:42)
[10:12:40 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.game.CommandHandler.handleCommand(CommandHandler.java:79)
[10:12:40 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.Main.onCommand(Main.java:87)
[10:12:40 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:12:40 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[10:12:40 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[10:12:40 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2306)
[10:12:40 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2117)
[10:12:40 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2098)
[10:12:40 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[10:12:40 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[10:12:40 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[10:12:40 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[10:12:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[10:12:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[10:12:40 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
[10:12:40 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[10:12:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[10:12:40 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
[10:12:40 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
[10:12:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[10:12:40 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1347)
[10:12:40 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
[10:12:40 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[10:12:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by tylermurphy534** [comment]
Are you on the latest build? If not update. If you are, try resting your config.yml file. I am currently unable to reproduce this error, as it loads fine for me currently. I uploaded a new build anyways, to try that too.

**Comment by Nesseley** [comment]
It was this build: https://github.com/tylermurphy534/KenshinsHideAndSeek/actions/runs/2278255053

The config loaded fine until I tried to change the CHAT to something else on that build. I could change all the other settings and reload, but once I changed that one it broke. 

I will be trying this one now: https://github.com/tylermurphy534/KenshinsHideAndSeek/actions/runs/2281455017
I still have problems with the Æ Ø Å, and they break the config after reloading. It seems this is what you do to break the config:

Lore of glow item:
`[Høyreklikk for å vise leteren!]` before reload
`[H�yreklikk for � vise leteren!]` reloaded once
`[H?yreklikk for ? vise leteren!]` reloaded twice.

Reloading after this again will break the config and send this error: 
```
[14:09:34 INFO]: Nesseley issued server command: /hs reload
[14:09:34 WARN]: java.lang.RuntimeException: Invalid configuration in config file: plugins\HideAndSeek\config.yml
[14:09:34 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.configuration.ConfigManager.<init>(ConfigManager.java:83)
[14:09:34 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.configuration.ConfigManager.create(ConfigManager.java:40)
[14:09:34 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.configuration.Config.loadConfig(Config.java:147)
[14:09:34 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.command.Reload.execute(Reload.java:42)
[14:09:34 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.game.CommandHandler.handleCommand(CommandHandler.java:79)
[14:09:34 WARN]:        at HideAndSeek-1.4.3.jar//net.tylermurphy.hideAndSeek.Main.onCommand(Main.java:87)
[14:09:34 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:09:34 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:09:34 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[14:09:34 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2306)
[14:09:34 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2117)
[14:09:34 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2098)
[14:09:34 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[14:09:34 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[14:09:34 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[14:09:34 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:09:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:09:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[14:09:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
[14:09:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1347)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[14:09:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by tylermurphy534** [comment]
Fixed in newest build

**Comment by Nesseley** [comment]
Chat: works
Actionbar: works
Title: Doesn't show any countdown at all :( Not sure if you know, but in 1.18 somtime they broke titles a bit, so you have to define the first line as an empty space for the title to show up, even if you only want text on line2 of titles. I'm guessing that's the problem here :)

**Comment by tylermurphy534** [comment]
added new build

**Comment by Nesseley** [comment]
It works! :D
