### ISSUE TITLE
Feature request: Better Spectator

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#42]
**Is your feature request related to a problem? Please describe.**
As of now spectators walk around fully visible. This makes it so they can find hiders and let seekers know where they are.

**Describe the solution you'd like**
Spectators should be invisible and have the ability to fly for a better spectator-feeling. (Not spectator gamemode, as I don't want them flying through the map itself.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by tylermurphy534** [comment]
added it in, there is no item to teleport to players yet, but your no longer in spectator gamemode

**Comment by Nesseley** [comment]
i was never in spectator gamemode, just defined that I did not want it :)

**Comment by Nesseley** [comment]
Invisible: yes


Still can't fly tho

**Comment by tylermurphy534** [comment]
Are you unable to double tap space to fly?

**Comment by Nesseley** [comment]
> Are you unable to double tap space to fly?

I can't fly at all no

**Comment by tylermurphy534** [comment]
uploaded new build!

**Comment by tylermurphy534** [comment]
uploaded a new build, I tried to enable flight before allowing you to fly lol, changed now

**Comment by tylermurphy534** [comment]
Is it possible you have another plugin interfering with the flying on the server? I just tested it the flying in the spigot api, and it seems to work fine.

Can you give me a list of plugins installed?

**Comment by tylermurphy534** [comment]
Also, are you sure when you join as a spectator, you cant double tap the spacebar to begin flight? If you touch the ground, It stops flight. You have to start flight again after you touch the ground.

**Comment by Nesseley** [comment]
I'm pretty sure I smashed my spacebar a hundred times :P 
(_I've played Minecraft for 10 years, I know how fly works_) :(

It's possible it's a plugin thing: 
Arcade, AttributeHider, BungeeTabListPlus, CMI, CMILib, DeluxeMenus, HideAndSeek, LuckPerms, Multiverse-Core, Multiverse-Inventories, NoJoinMessage*, Parkour, PlaceholderAPI, ProtocolLib, TreysDoubleJump, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldGuard

Using CMI to to /fly works, which turns fly to on, then I can fly in the world

**Comment by tylermurphy534** [comment]
I believe TreysDoubleJump is causing issues for you. When the plugin is downloaded, I can only fly with the plugins /fly command. And when my plugin enables flight, I only do a long jump (from TreysDoubleJump) instead of starting to fly.

Try removing TreysDoubleJump and seeing if that works! :)

**Comment by Nesseley** [comment]
I didn't remove the plugin (just to test if this build changed something)

With the new build and when I type `fly` I can fly, and `no fly` turns it back off as both hider and seeker.

As a spectator I can't fly with or without OP (I have no perms to use Treys Double Jump if I'm not OP) 
`fly` and `no fly` works for spectator as well.

I removed TDJ and restarted the server. Spectator still can't fly by default.

**Comment by tylermurphy534** [comment]
I uploaded a new build that constantly re enables flight on spectators, so hopefully it will work now.

**Comment by Nesseley** [comment]
Hm, what if you just make the spectator do a command after joining to enable flight? 
`/hs spectator togglefly` or something that you can only use when a spectator. 

With just typing `fly` I can land and fly as much as I'd like. It's not like it turns off on it self

**Comment by Nesseley** [comment]
Newest build:

Still can't fly when I join. Typing `fly` makes me fly, but I am no longer able to doubletap spacebar to fall back down. Probably since you keep enabling fly.

**Comment by tylermurphy534** [comment]
I haven't uploaded a new build to work on this yet lol, will soon though

**Comment by tylermurphy534** [comment]
Pushed to latest build. Spectators now spawn with two items.

One toggles flight, and one opens a menu to teleport to other players!

**Comment by Nesseley** [comment]
this message spams the console like crazy when a player has joined as a spectator.
```
[21:52:31 WARN]: [HideAndSeek] Task #8 for HideAndSeek v1.4.3 generated an exception
java.lang.NullPointerException: Cannot invoke "net.tylermurphy.hideAndSeek.game.CustomBoard.setLine(String, String)" because "board" is null
        at net.tylermurphy.hideAndSeek.game.Board.createGameBoard(Board.java:291) ~[HideAndSeek-1.4.3.jar:?]
        at net.tylermurphy.hideAndSeek.game.Board.reloadGameBoards(Board.java:316) ~[HideAndSeek-1.4.3.jar:?]
        at net.tylermurphy.hideAndSeek.game.Game.whilePlaying(Game.java:303) ~[HideAndSeek-1.4.3.jar:?]
        at net.tylermurphy.hideAndSeek.game.Game.onTick(Game.java:219) ~[HideAndSeek-1.4.3.jar:?]
        at net.tylermurphy.hideAndSeek.Main.onTick(Main.java:94) ~[HideAndSeek-1.4.3.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
``` 
  
  
Clicking with the fly item gives this message in the actionbar: 
`FLYING_ENABLED/DISABLED is not found in localization.yml. This is a plugin issue, please report it.`

However, the messages are in my file:
```
  FLYING_ENABLED: "&l&bFlying Enabled"
  FLYING_DISABLED: "&l&bFlying Disabled"
```

**Comment by tylermurphy534** [comment]
Fixed in the latest build, 1.4.3 RC1.

**Comment by Nesseley** [comment]
**ISSUE 3** `The items are removed from the spectator inventory once the game starts if you enter the game before the countdown has ended. `is still a problem.

**Comment by tylermurphy534** [comment]
Hopefully fixed in 1.5.0 Release Candidate 4. I had a misplaced `return` keyword instead of `continue`....

**Comment by tylermurphy534** [comment]
Uploaded a Fix in Release Candidate 4.1.
